using TeaShopTelegramBot.Commands.GeneralCommands.GeneralcallbackCommands;
using TeaShopTelegramBot.Commands.GeneralCommands.GeneralCallbackCommands;
using TeaShopTelegramBot.Commands.GeneralCommands.GeneralTextCommands;
using TeaShopTelegramBot.Commands.HerbCommands.CallbackHerbCommands;
using TeaShopTelegramBot.Commands.HerbCommands.TextHerbCommands;
using TeaShopTelegramBot.Commands.HoneyCommands.CallbackHoneyCommands;
using TeaShopTelegramBot.Commands.HoneyCommands.TextHoneyCommands;
using TeaShopTelegramBot.Commands.OrderCommands.CallbackOrderCommands;
using TeaShopTelegramBot.Commands.OrderCommands.TextOrderCommands;
using TeaShopTelegramBot.Commands.ProductCommands.CallbackProductCommands;
using TeaShopTelegramBot.Commands.ProductCommands.TextProductCommands;
using TeaShopTelegramBot.Commands.TeaCommands.CallbackTeaCommands;
using TeaShopTelegramBot.Commands.TeaCommands.TextTeaCommands;
using TeaShopTelegramBot.Common.Abstractions;
using TeaShopTelegramBot.Common.Servicies;
using TeaShopTelegramBot.Messages.OrderMessages;
using TeaShopTelegramBot.Messages.TeaMessages;

namespace Microsoft.Extensions.DependencyInjection;

public static class ConfigureService
{
    public static IServiceCollection AddTelegramBotServices(this IServiceCollection services)
    {
        services.AddMemoryCache();
        services.AddSingleton<TelegramBot>();
        services.AddScoped<IMemoryCachService, MemoryCachService>();
        services.AddScoped<ICommandAnalyzer, CommandAnalyzer>();
        services.AddScoped<ITextCommandService, TextCommandService>();
        services.AddScoped<BaseTextCommand, StartTextCommand>();
        services.AddScoped<BaseTextCommand, ProductAddTextCommand>();
        services.AddScoped<BaseTextCommand, HoneyNameTextCommand>();
        services.AddScoped<BaseTextCommand, HoneyDescriptionTextCommand>();
        services.AddScoped<BaseTextCommand, HoneyPriceTextCommand>();
        services.AddScoped<BaseTextCommand, HoneyCountTextCommand>();
        services.AddScoped<BaseTextCommand, HoneyPhotoTextCommand>();
        services.AddScoped<BaseTextCommand, TeaNameTextCommand>();
        services.AddScoped<BaseTextCommand, TeaPriceTextCommand>();
        services.AddScoped<BaseTextCommand, TeaCountTextCommand>();
        services.AddScoped<BaseTextCommand, TeaPhotoTextCommand>();
        services.AddScoped<BaseTextCommand, TeaDescriptionTextCommand>();
        services.AddScoped<BaseTextCommand, HerbNameTextCommand>();
        services.AddScoped<BaseTextCommand, HerbPriceTextCommand>();
        services.AddScoped<BaseTextCommand, HerbDescriptionTextCommand>();
        services.AddScoped<BaseTextCommand, HerbCountTextCommand>();
        services.AddScoped<BaseTextCommand, HerbPhotoTextCommand>();
        services.AddScoped<BaseTextCommand, ProductEditTextCommand>();
        services.AddScoped<BaseTextCommand, LanguageTextCommand>();
        services.AddScoped<BaseTextCommand, MenuTextCommand>();
        services.AddScoped<BaseTextCommand, CartTextCommand>();
        services.AddScoped<BaseTextCommand, NumberTextCommand>();
        services.AddScoped<BaseTextCommand, UserNameTextCommand>();
        services.AddScoped<BaseTextCommand, AddressTextCommand>();
        services.AddScoped<BaseTextCommand, SmallWholesaleTextCommand>();
        services.AddScoped<BaseTextCommand, EditTeaDescriptionTextCommand>();
        services.AddScoped<BaseTextCommand, EditTeaCountTextCommand>();
        services.AddScoped<BaseTextCommand, EditTeaPriceTextCommand>();
        services.AddScoped<BaseTextCommand, EditHerbDescriptionTextCommand>();
        services.AddScoped<BaseTextCommand, EditHerbPriceTextCommand>();
        services.AddScoped<BaseTextCommand, EditHerbCountTextCommand>();
        services.AddScoped<BaseTextCommand, EditHoneyDescriptionTextCommand>();
        services.AddScoped<BaseTextCommand, EditHoneyCountTextCommand>();
        services.AddScoped<BaseTextCommand, EditHoneyPriceTextCommand>();
        services.AddScoped<BaseTextCommand, HerbDiscountTextCommand>();
        services.AddScoped<BaseCallbackCommand, TeaAddCallbackCommand>();
        services.AddScoped<BaseTextCommand, TeaDiscountTextCommand>();
        services.AddScoped <BaseTextCommand, HoneyDiscountTextCommand>();
        services.AddScoped<BaseTextCommand, DiscountTextCommand>();
        services.AddScoped<BaseTextCommand, DiscountsTextCommand>();
        services.AddScoped<BaseTextCommand, EditDiscountTextCommand>();
        services.AddScoped<BaseCallbackCommand, ProductAddCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HerbAddCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HoneyAddCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HoneyWeightCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HoneyRegressionCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, TeaTypeCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, TeaRegressionCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, TeaWeightCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, TeaFormCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HerbRegionCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HerbRegressionCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HerbWeightCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, TeaSaveCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HerbSaveCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HoneySaveCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, LanguageCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, TeaTypesForMenuCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, MenuCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, GetTeasInStockCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, GetHerbsInStockCallbackCommand>();        
        services.AddScoped<BaseCallbackCommand, HerbRegionsForMenuCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, GetHoneyInStockCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, CartCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, TeaAddToCartCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HerbAddToCartCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HoneyAddToCartCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, PaymentMethodCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, DeliveryMethodCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, NumberCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, AddressCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, SaveContactsCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, OrderConfirmCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, InfoCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, RemoveProductFromOrderCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, TeaTypeForEditCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, EditProductCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, GetTeasForEditCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, EditOptionsTeaCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, EditingTeaParametrsCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, RemoveTeaFromDbCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, HerbRegionsForEditCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, GetHerbsForEditCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, EditOptionsHerbCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, EditingHerbParametrsCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, RemoveHerbFromDbCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, GetHoneyForEditCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, EditOptionsHoneyCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, EditingHoneyParametrsCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, RemoveHoneyFromDbCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, DiscountCallbackCommand>();
        services.AddScoped<BaseCallbackCommand, GetDiscountProductsCallbackCommand>();

        return services;
    }
}
