global using TeaShopTelegramBot.Common;
global using Telegram.Bot;
global using Telegram.Bot.Types;
global using Telegram.Bot.Types.ReplyMarkups;
global using Telegram.Bot.Types.Enums;
global using TeaShopTelegramBot.Common.Interfaces;
global using Application.Common.EnumParsers;
global using Domain.Enums;
global using TeaShopTelegramBot.Common.Servicies;
